import Foundation

/// A chapter version, rendered as `v1.2.0`.
///
/// Beckit only ever uses the three numeric components — no prerelease or build
/// metadata — because versions are generated by the app, never hand-authored.
public struct SemanticVersion: Sendable, Hashable, Comparable, Codable,
                               CustomStringConvertible {
    public var major: Int
    public var minor: Int
    public var patch: Int

    public static let initial = SemanticVersion(1, 0, 0)

    public init(_ major: Int, _ minor: Int, _ patch: Int) {
        self.major = major
        self.minor = minor
        self.patch = patch
    }

    /// Parses `v1.2.0` or `1.2.0`. Returns nil for anything else.
    public init?(_ string: some StringProtocol) {
        var text = Substring(string)
        if text.first == "v" || text.first == "V" { text = text.dropFirst() }

        let parts = text.split(separator: ".", omittingEmptySubsequences: false)
        guard parts.count == 3 else { return nil }

        var numbers: [Int] = []
        numbers.reserveCapacity(3)
        for part in parts {
            // Reject "01", "+1", " 1" and similar so that round-tripping a
            // parsed version always reproduces the original string.
            guard !part.isEmpty, part.allSatisfy(\.isNumber),
                  part.count == 1 || part.first != "0",
                  let value = Int(part)
            else { return nil }
            numbers.append(value)
        }
        self.init(numbers[0], numbers[1], numbers[2])
    }

    public var description: String { "v\(major).\(minor).\(patch)" }

    public func bumped(_ change: ChangeSignificance) -> SemanticVersion {
        switch change {
        case .major: SemanticVersion(major + 1, 0, 0)
        case .minor: SemanticVersion(major, minor + 1, 0)
        case .patch: SemanticVersion(major, minor, patch + 1)
        }
    }

    public static func < (lhs: Self, rhs: Self) -> Bool {
        (lhs.major, lhs.minor, lhs.patch) < (rhs.major, rhs.minor, rhs.patch)
    }
}

/// How much a save changed the text. `nil` from the classifier means the edit
/// was too small to be worth a new version at all.
public enum ChangeSignificance: String, Sendable, Hashable, Codable, CaseIterable {
    case major, minor, patch
}
