import BeckitGit
import BeckitKit
import SwiftUI

/// First run, and the screen you come back to between books.
struct WelcomeView: View {
    @Environment(Library.self) private var library

    var body: some View {
        HStack(spacing: 0) {
            introduction
            Divider()
            sidebar
        }
    }

    private var introduction: some View {
        VStack(alignment: .leading, spacing: 16) {
            Spacer()

            AppMark(size: 76)

            VStack(alignment: .leading, spacing: 8) {
                Text("Beckit")
                    .displayText(size: 44)

                Text("Write a book. Keep every version. Sync it to GitHub.")
                    .font(.title3)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }

            Spacer()

            if let account = library.account {
                Label("Signed in as \(account.login)", systemImage: "checkmark.circle.fill")
                    .foregroundStyle(.secondary)
                    .font(.callout)
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .leading)
        .padding(40)
        // Lets the wash behind the mark run under the window's translucent
        // chrome instead of stopping at the content edge.
        .backgroundExtensionEffect()
    }

    private var sidebar: some View {
        VStack(alignment: .leading, spacing: 16) {
            // Opening a book never requires GitHub. Beckit 3.x demanded a
            // sign-in before it would show you anything, which meant no
            // offline first run and no way to try it at all without an
            // account. Sync is a feature of a book, not a gate in front of one.
            Button {
                library.promptToOpenBook()
            } label: {
                Label("Open or Create a Book…", systemImage: "folder")
                    .frame(maxWidth: .infinity, alignment: .leading)
            }
            .buttonStyle(.glassProminent)
            .controlSize(.large)

            if !library.isSignedIn {
                Text("Connect GitHub to sync and back up your work.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                SignInView()
            }

            if !library.recentBooks.isEmpty {
                Text("Recent")
                    .font(.caption.weight(.semibold))
                    .foregroundStyle(.secondary)
                    .padding(.top, 4)

                ForEach(library.recentBooks, id: \.self) { url in
                    Button {
                        library.open(url)
                    } label: {
                        VStack(alignment: .leading, spacing: 1) {
                            Text(url.lastPathComponent).lineLimit(1)
                            Text(url.deletingLastPathComponent().path(percentEncoded: false))
                                .font(.caption)
                                .foregroundStyle(.tertiary)
                                .lineLimit(1)
                                .truncationMode(.head)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(.vertical, 2)
                    }
                    .buttonStyle(.accessoryBar)
                }
            }

            Spacer()
        }
        .padding(24)
        .frame(width: 330)
        // No opaque panel colour. The pane is a glass layer over the wash on
        // the left, so it takes its tone from what is behind it — which is the
        // point of the material, and something a flat fill would defeat.
        .glassEffect(
            .regular,
            in: ConcentricRectangle(uniformLeadingCorners: .concentric))
        .padding(.vertical, 12)
        .padding(.trailing, 12)
    }
}

/// The app mark: the traced contours filled, on a rounded ground.
///
/// Geometry comes from `MarkGeometry`, which is generated by
/// `Scripts/trace-reference.swift` and compiled into both this app and the icon
/// generator. The mark in the window and the icon in the Dock are therefore the
/// same contours — there is no second copy to keep in step.
struct AppMark: View {
    var size: CGFloat

    static let ink = Color(red: 0.839, green: 0.278, blue: 0.608)
    static let groundTop = Color(red: 1.000, green: 1.000, blue: 1.000)
    static let groundBottom = Color(red: 0.976, green: 0.969, blue: 0.973)

    /// How much to thicken the mark, in points. Mirrors `embolden(for:)` in the
    /// icon generator: below roughly 192pt the traced strokes fall under a
    /// pixel and antialias into pale grey, and stroking the filled outline
    /// grows every edge outward by half of this.
    static func embolden(for size: CGFloat) -> CGFloat {
        switch size {
        case ..<24: 1.1
        case ..<48: 1.3
        case ..<96: 1.0
        case ..<192: 0.6
        default: 0
        }
    }

    var body: some View {
        ZStack {
            RoundedRectangle(cornerRadius: size * 0.225, style: .continuous)
                .fill(LinearGradient(
                    colors: [Self.groundTop, Self.groundBottom],
                    startPoint: .top, endPoint: .bottom))

            TracedMark()
                .fill(Self.ink, style: FillStyle(eoFill: true))
                .overlay {
                    // Emboldening pass, matching the icon generator.
                    TracedMark().stroke(Self.ink, style: StrokeStyle(
                        lineWidth: Self.embolden(for: size),
                        lineCap: .round, lineJoin: .round))
                }
        }
        .frame(width: size, height: size)
        .shadow(color: .black.opacity(0.10), radius: size * 0.05, y: size * 0.02)
    }
}

/// The traced mark, scaled into `rect`.
///
/// Filled with the even-odd rule, so the holes in the artwork come out as holes
/// without being treated specially. SwiftUI shapes already run top-left down,
/// which is the space `MarkGeometry` is written in, so there is no flip here.
struct TracedMark: Shape {
    func path(in rect: CGRect) -> Path {
        let unit = min(rect.width, rect.height) / MarkGeometry.canvas
        var path = Path()
        for contour in MarkGeometry.contours {
            guard let first = contour.first else { continue }
            path.move(to: CGPoint(
                x: rect.minX + first.x * unit, y: rect.minY + first.y * unit))
            for point in contour.dropFirst() {
                path.addLine(to: CGPoint(
                    x: rect.minX + point.x * unit, y: rect.minY + point.y * unit))
            }
            path.closeSubpath()
        }
        return path
    }
}

/// GitHub device flow. The writer sees a short code, types it into their
/// browser, and the app notices when they are done.
struct SignInView: View {
    @Environment(Library.self) private var library

    @State private var device: GitHubClient.DeviceCode?
    @State private var isWorking = false
    @State private var failure: String?

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            if let device {
                Text("Enter this code on GitHub")
                    .font(.callout.weight(.medium))

                HStack {
                    Text(device.userCode)
                        .font(.system(.title2, design: .monospaced).weight(.semibold))
                        .textSelection(.enabled)
                    Spacer()
                    Button {
                        NSPasteboard.general.clearContents()
                        NSPasteboard.general.setString(device.userCode, forType: .string)
                    } label: {
                        Image(systemName: "document.on.document")
                    }
                    .buttonStyle(.borderless)
                    .help("Copy code")
                }
                .padding(12)
                .glassEffect(
                    .regular,
                    in: ConcentricRectangle(corners: .concentric, isUniform: true))

                Link("Open github.com/login/device", destination: device.verificationURI)

                HStack(spacing: 6) {
                    ProgressView().controlSize(.small)
                    Text("Waiting for you to authorise…")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            } else {
                Button(action: start) {
                    Label("Sign in with GitHub", systemImage: "person.badge.key")
                        .frame(maxWidth: .infinity, alignment: .leading)
                }
                .buttonStyle(.glass)
                .controlSize(.large)
                .disabled(isWorking)
            }

            if let failure {
                Text(failure)
                    .font(.caption)
                    .foregroundStyle(.orange)
            }
        }
    }

    private func start() {
        isWorking = true
        failure = nil

        Task {
            defer { isWorking = false }
            do {
                let client = GitHubClient()
                let device = try await client.requestDeviceCode()
                self.device = device

                // Open the browser for them; the code is on screen either way.
                NSWorkspace.shared.open(device.verificationURI)

                let token = try await client.pollForToken(device)
                try await Credentials.shared.set(token)
                library.signedIn(as: try await client.account(token: token))
                self.device = nil
            } catch {
                self.device = nil
                failure = error.localizedDescription
            }
        }
    }
}
